POST /auth/login
Host: localhost:8080
Content-Type: application/json

{
  "email": "yusuf1@gmail.com",
  "password": "111111"
}

###
POST /auth/register
Host: localhost:8080
Content-Type: application/json

{
  "username": "hansa",
  "email": "hansa@gmail.com",
  "password": "1234"
}

###
POST /auth/forgot-password
Host: localhost:8080
Content-Type: application/json

{
  "email": "hansa@gmail.com"
}
###
POST /auth/reset-password
Host: localhost:8080
Content-Type: application/json

{
  "otp": "557261",
  "new_password": "2222",
  "confirm_password": "2222"
}

###
GET /users/1
Host: localhost:8080

###
GET /users?search=an&sort=descending
Host: localhost:8080

###
DELETE /users/3
Host: localhost:8080

###
PATCH /users/2
Host: localhost:8080
Content-Type: application/json
{
  "username": "dansa",
  "email": "hansaaaaaa@gmail.com"
}
