POST /auth/login
Host: localhost:8080
Content-Type: application/json

{
  "email": "yusuf1@gmail.com",
  "password": "111111"
}

###
POST /auth/register
Host: localhost:8080
Content-Type: application/json

{
  "username": "hansa",
  "email": "hansa@gmail.com",
  "password": "1234"
}

###
POST /auth/forgot-password
Host: localhost:8080
Content-Type: application/json

{
  "email": "hansa@gmail.com"
}
###
POST /auth/reset-password
Host: localhost:8080
Content-Type: application/json

{
  "otp": "557261",
  "new_password": "2222",
  "confirm_password": "2222"
}

###
GET /users/7
Host: localhost:8080

###
GET /users?search=an&sort=descending&page=2
Host: localhost:8080

###
DELETE /users/3
Host: localhost:8080

###
PATCH /users/7 HTTP/1.1
Host: localhost:8080
Content-Type: multipart/form-data; boundary=----WebkitBoundary

------WebkitBoundary
Content-Disposition: form-data; name="username"

yusuf33
------WebkitBoundary
Content-Disposition: form-data; name="email"

yusuf33@gmail.com
------WebkitBoundary
Content-Disposition: form-data; name="password"

yusuf33
------WebkitBoundary
Content-Disposition: form-data; name="picture"; filename="ccc.png"
Content-Type: image/png

< ./ppp.png
------WebkitBoundary--

###
POST /users HTTP/1.1
Host: localhost:8080
Content-Type: multipart/form-data; boundary=----WebkitBoundary

------WebkitBoundary
Content-Disposition: form-data; name="username"

yusuf22
------WebkitBoundary
Content-Disposition: form-data; name="email"

yusuf22@gmail.com
------WebkitBoundary
Content-Disposition: form-data; name="password"

yusuf22
------WebkitBoundary
Content-Disposition: form-data; name="picture"; filename="ccc.png"
Content-Type: image/png

< ./ccc.png
------WebkitBoundary--